Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"

    # Natural scrolling
    Option "NaturalScrolling" "true"

    # Tap-to-click
    Option "Tapping" "true"

    # Tap-and-drag
    Option "TappingDrag" "true"
EndSection
